// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACgdAqU3bN8D41Ve6dOSN77RaHex1llp8',
    appId: '1:959650735008:web:77d88f7219432972307ac5',
    messagingSenderId: '959650735008',
    projectId: 'myeshop-ff46b',
    authDomain: 'myeshop-ff46b.firebaseapp.com',
    storageBucket: 'myeshop-ff46b.appspot.com',
    measurementId: 'G-4GW6M9G23L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8g1BFEr6FueiiF4K7F7gNIwr2E41E2SA',
    appId: '1:959650735008:android:31e7fbc4137e5819307ac5',
    messagingSenderId: '959650735008',
    projectId: 'myeshop-ff46b',
    storageBucket: 'myeshop-ff46b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg0XmftqucHriCSHGIzlyfdjBPtLcD5g',
    appId: '1:959650735008:ios:8707e5cdb85c0030307ac5',
    messagingSenderId: '959650735008',
    projectId: 'myeshop-ff46b',
    storageBucket: 'myeshop-ff46b.appspot.com',
    androidClientId: '959650735008-a92falp8v9uaufjvid4qs6kftm9gp61t.apps.googleusercontent.com',
    iosClientId: '959650735008-9rh1mavgn92de7q18f4q310rtb9h2u21.apps.googleusercontent.com',
    iosBundleId: 'com.example.eShop',
  );

}